#!/bin/sh
set -e

if command -v lsb_release >/dev/null 2>&1; then
    case "$(lsb_release --id --short)" in
	Ubuntu|Debian)
	    for package in python3-venv python3-dev libxml2-dev libxslt1-dev python3-libvirt genisoimage pkg-config libvirt-dev gcc; do
		if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
                    # add a space after old values
		    missing="${missing:+$missing }$package"
		fi
	    done
	    if [ -n "$missing" ]; then
		echo "$0: missing required packages, please install them:" 1>&2
		echo "  sudo apt-get install $missing"
		exit 1
	    fi
	    ;;
    esac
fi

test -d virtualenv || python3 -m venv virtualenv
./virtualenv/bin/pip install -r requirements-dev.txt
./virtualenv/bin/pip install -e .
